name = "LaskaStats"
uuid = "de767ba9-e829-4e7c-bf82-062dc00bf36c"
authors = ["Elias Sj√∂lin", "<elias.sjolin@gmail.com>"]
version = "1.0.5"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
KissSmoothing = "23b0397c-cd08-4270-956a-157331f0528f"
LaskaCore = "9ad29ce2-7782-4744-ab48-6ef9cc0286bb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SingularSpectrumAnalysis = "77f5812f-bd1f-5f6e-9b72-07b28d8bbbc3"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TruncatedMVN = "502039d7-87d7-456d-8cc8-96307cceeee2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Aqua = "0.8"
DSP = "0"
DataStructures = "0"
Distributions = "0"
FFTW = "1"
ImageFiltering = "0"
InvertedIndices = "1"
KissSmoothing = "1"
LaskaCore = "0"
LinearAlgebra = "1"
NaNMath = "1"
Optimisers = "0"
Random = "1"
Reexport = "1"
SingularSpectrumAnalysis = "0"
SpecialFunctions = "2"
StaticArrays = "1"
Statistics = "1"
StatsBase = "0"
Test = "1"
TruncatedMVN = "1"
Unitful = "1"
Zygote = "0"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
